<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 5" tests="0" total_time="Finished in: 0.00 secs."/>
<test location="C:\Workspace_Python\Python06_mongo\mongo\pymongo.py" status="error" test="pymongo" time="0">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "C:\Users\chohyeonjunn\.p2\pool\plugins\org.python.pydev.core_7.5.0.202001101138\pysrc\_pydev_runfiles\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:/Workspace_Python/Python06_mongo/mongo\pymongo.py", line 3, in <module>
    from pymongo import MongoClient
ImportError: cannot import name 'MongoClient' from partially initialized module 'pymongo' (most likely due to a circular import) (C:/Workspace_Python/Python06_mongo/mongo\pymongo.py)
ERROR: Module: pymongo could not be imported (file: C:\Workspace_Python\Python06_mongo\mongo\pymongo.py).
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="Python06_mongo pymongo.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
